pipeline:
  install:
    image: node:12.16.1-alpine
    commands:
      - yarn

  spell-check:
    image: node:12.16.1-alpine
    commands:
      - yarn spell-check

  type-check:
    image: node:12.16.1-alpine
    commands:
      - yarn type-check

  lint:
    image: node:12.16.1-alpine
    commands:
      - yarn lint
